server:
  port: 8282
  servlet:
    context-path: /api

spring:
  application:
    name: book-app

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
  security:
    sessions: never