server:
  port: 8282

spring:
  application:
    name: book-app

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discUser:secret@localhost:8761/eureka/

management:
  security:
    sessions: never