server:
  port: 8283

spring:
  application:
    name: rating-app
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
  security:
    sessions: never